var TRANSLATION = {
  lang: 'en',
  en: {
    ask: 'ask',
    name: 'name',
    from: 'from',
    message: 'massege',
    send: 'send',
    cancel: 'cancel',
    remove: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    export: 'export',
    messTitleAdmin: 'Message for moderation',
  },
  es: {
    ask: 'preguntar',
    name: 'Nombre',
    from: 'De',
    message: 'mensaje',
    send: 'Enviar',
    cancel: 'Borrar',
    remove: 'remove',
    disallow: 'rechazar',
    allow: 'permitir' ,
    dir: 'ltr',
    export: 'export'
  },
  ru: {
    ask: 'спросить',
    name: 'Имя',
    from: 'Город',
    message: 'Ваше сообщение',
    send: 'Послать',
    cancel: 'Отчистить',
    remove: 'удалить',
    disallow: 'отказать',
    allow: 'одобрить',
    dir: 'ltr',
    export: 'export'
  },
  he: {
    ask: 'לשאול',
    name: 'שם',
    from: 'מ',
    message: 'הודעה',
    send: 'לשלוח',
    cancel: 'לבטל',
    remove: 'להסיר',
    disallow: 'לפסול',
    allow: 'להתיר',
    dir: 'rtl',
    export: 'export'
  }
};
