var TRANSLATION = {
  lang: 'en',
  en: {
    askBtn: 'ask',
    nameInput: 'name',
    fromInput: 'from',
    messageInput: 'massege',
    sendBtn: 'send',
    cancelBtn: 'cancel',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation',
  },
  es: {
    askBtn: 'preguntar',
    nameInput: 'Nombre',
    fromInput: 'De',
    messageInput: 'mensaje',
    sendBtn: 'Enviar',
    cancelBtn: 'Borrar',
    removeBtn: 'remove',
    disallow: 'rechazar',
    allow: 'permitir' ,
    dir: 'ltr',
    exportBtn: 'export'
  },
  ru: {
    askBtn: 'спросить',
    nameInput: 'Имя',
    fromInput: 'Город',
    messageInput: 'Ваше сообщение',
    sendBtn: 'Послать',
    cancelBtn: 'Отменить',
    removeBtn: 'удалить',
    disallow: 'отказать',
    allow: 'одобрить',
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Модерация',
  },
  he: {
    askBtn: 'לשאול',
    nameInput: 'שם',
    fromInput: 'מ',
    messageInput: 'הודעה',
    sendBtn: 'לשלוח',
    cancelBtn: 'לבטל',
    removeBtn: 'להסיר',
    disallow: 'לפסול',
    allow: 'להתיר',
    dir: 'rtl',
    exportBtn: 'export'
  }
};

